apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: claude-auth
  namespace: a2w-lucas
spec:
  encryptedData:
    api-key: AgCbgURKzl2D+xTnM9RykvKNsR+5Ute9pKLmszXt8SQDds/Uv6gqDWNPiytmI22SByh6X73j/jOiCk2p+8TM6Nan9T1roqbGBY0XmCA2tM0R4gWi2khKbuADg/SF3xyTY8wV1/9NGGSqRt+dX6waHR+AJ+RWXSpgbHwBCqeHUlIihArSGTzRrgoD/UbeXGLfTSWMFKTFzBm34uGZjEK4JRIJ0w2sfxbAR8VTNPbFd+rAXSkVQ2SfeOC71lCf+ljLJmwwyzZwPyxZSDCfiTo3D2RiMlWlkxVX907E7r+CydFmTH7QMPBPHSCqNzrmiSFJLi8s2YMPs/hWXSHCPbdri9JFFAcc6R/0uicIJAgjxpDlzJ8+5IByLVzFS7m9MkOPHMXIikreFSkrPC+Fk6+T4KNZvsfPObvk/wYs3GUlDJCS+9fusH0sAVJyzG9DUTMpDr3afbIhd3OObvOZTCX7vcrJZtJtxC6OI/sFggBhJSFgMWAflFfZQlPRNIDDLQWYWS3KFLMEvwuduXDjiPE5B5emynFR4PWIsEJmINcfv1u0CZki/25DdjLRggn8v3C0nvAvIx38CnGDb2bTk/1ZXRCL6/YOvsEDr761yEBf4Tg1k/XZGUnKLDXJ5qfDDFU1oNsJzhk49R37bTsq3B6CwHTn6SoVhNqGdJs/5VBE8P5TpD13XqJrNDM4gCC9XxPYE3Ihb8hBmEGUXfQq5qzIlapKg9XbzLePNU7m1jFsOf5n//XI9qEJr6D3cJqhwpklOVK4Af/xjQGNR/T8z+RNvBLi2UZP7rMUksGubqGwm/YsEd04ZMHoNj4I2OIP9X8ofTzMeMXmyRKVIfvt4Pw=
  template:
    metadata:
      creationTimestamp: null
      name: claude-auth
      namespace: a2w-lucas
