apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeden-api
  labels:
    app: kubeden-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeden-api
  template:
    metadata:
      labels:
        app: kubeden-api
    spec:
      containers:
      - name: kubeden-api
        image: registry.digitalocean.com/kubeden/kubeden-api:a2ca675
        ports:
        - containerPort: 5173
        env:
        - name: GITHUB_OWNER
          value: "kubeden"
        - name: GITHUB_REPO
          value: "kubeden"