apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgCnzg/AAqCWyiOmGRMLL0TdMSCREc8Tg5kHdbL1XYRDRsmhr8gpxutq/h+1FCV0Jkw0edjn1H9x2KkLuwnNmF6w/HnQwiXgwNF7eJ8nhtiY4DkuXIGs52rzDfG4u0t3Uw27PnTboFPBbMbZCHsF0V1ezxIXFC7ilVDf2l7QInfyv+XCJ3KpocwH7h2wE/GMMs8OGMH9YZWgHUXNtAYJK2wMwSMwC1Va5WzmSrvUDZ7AnR9Y15LO5TILk8u2giz4vQhTeDCe6iQQ0wQTapARm9oax8UL07SlgdugN1VaFG3yI+TKeYB+MzHNK/bV01Qq6qc1sACMThcrs/KptJWLGaOcc2Uyi/kJmYjfieWufW1H+p4HJicpKIsRijOv+IqiDmihoKy9/TIhXlGUtl2sMY4fZdohvGAcRK0CMY47Ec/t4aqTmDYXcEWvxPu+jAwYsVNAGmWojQzyMywPRmjcQpVy4kE8K+urSnmdJtEyEnHzyXXdndW3/I7FSVHWWGoaNXwE3/yTng3sHOTkkF37l7vklZqrl7KuvaG9Cigere1fvJ2N4g3ogbldfcvmWAAU84hKBcS6pQic4fN+q7kNea2jiZDZu7M/OG88xPTNEBSou3waw9jnmvZq0etSdGmMTW5JynbxLQ7batdw1PehHmiiwvF5gi2tu2qi3XiMgJzFbvSW+LxWwS0/JafmZnEFomtgZ364dx4AI83/p9VlY9MUr8TvviOn5VI7MgbLb+S3fuGxxJbF4Byd
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
    type: Opaque
