---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: claude-auth
  namespace: a2w-lucas
spec:
  encryptedData:
    api-key: AgC3eACxbILeJ7O1+RmdqZsLXuXF6yj4Qj1+E/e+6QweDR63e5rkQ67wFK5QhgsDEz8W/MZ+5EYrAhdX9Ab6inLo65asJ9JnN/Vjk6JqQZETvAoEtFbTNEOU4xChhLHeTOTPBRmvyYce8sf+WiN/B0fq8c+8JUxJU7BbWtUy94IyUg2LwRxNtfzeCMgSLX/MsRhnda2zydaYpE5FKB2GrMdxf/Kx7iRVpIM9ydFHoBLSZv/CV4YDfKIGHob/fYLXGTHfLC8w8tkuPDSobUNxGHbJClDD3EhDyEgy2gm8yeeTFPFwCGh1YiYyfpQ6p6ASPToST5wbZw4Hpo6/kg1JjhAtGA8a0o7e+EVlPYTfPn86zRq88F4b4tJDboHpdvi2ulI4/Waxl0qXc3sud3dhT0bYkarCkb/aslXBgqQnonTc3DJ93rZlqFbJIdRWKi9Xt25/k99WxdUcZRxEzN7NhCz5cqFWxeUK17LBHVOePsWeAgqABPtlb8ayNj+7I4vQ5foUI5a1epgBjmtBvZuo/hy0MsdaF2tzMiju1IIMJxF/po1fJfRSSHhf8aMIXEhL4UMF9xv7cz5l7Y2Ovma4AIDeLhzYl8CcenX2shLpLvDvbuJ1LHwrTsySagYNKMgNIXvKtRJ/f2W5u5CLo0zbZlfzSx3+eQAG8Ex8tWez2ftq+cB333IG1W3XqtovadVn3Le7Qcxj4huHrzCotVRsRhH8aUpGuIfKp8EKE96A08UwUE2Ii6BCyrgsMIfVZ+mPDNs4E7Edemxg14/lPSVWFcLROzpJ2sqe4zYkL8iwwTWV9STllXbjBmBdfal4QmAm9oAedKztnDf0lhiwqGk=
  template:
    metadata:
      creationTimestamp: null
      name: claude-auth
      namespace: a2w-lucas
