apiVersion: v1
kind: Service
metadata:
  name: lucas-docs
  namespace: a2w-lucas
spec:
  selector:
    app: lucas-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
