apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: a2w-sre
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeden/kubeden.git
    targetRevision: HEAD
    path: kubernetes/argocd/platform/a2w-sre
  destination:
    server: https://kubernetes.default.svc
    namespace: a2w-sre
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
