---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook
  namespace: a2w-sre
spec:
  encryptedData:
    webhook-url: AgCpYrffQ8cHsK4dO2jg9gDk6RKU66S/y5og+bBr3m/Z9DkA5ns+l7nCQisPKKpzR9TGGnAeV2/+aMYSw33/hPPao46X/hfnv5ORndtZFSKABo+JADvg1pKqipm89+0mU7WCmiK+qpPFMrGZQFjMB7WkZRC+bJLk8RFoGC3vMdAHie2ZgyiURjvARnjiqcOtcyxblBmsr57pYLuGgOLQ9bF09a09iAl55H2akEMrDkFFBwmMi8yzIFsxjWJxI2I8JFkTevQ7JhQV8BjCeWP1rcBZSD7yG7DU4PqAUtPX5NgODtqdJYRgF+Jq055CBpr0ZwCWe7AKcyPUSJyvqeWD88WBUxs6dkz+DdbML9ntbYtZG8RtEH3c51V9D8pkTFpCP5/RXUb7FhduIRVHZZU6njBd4gRjzgk1IB96ap+/cGKVXeyH8sTpzo2BQgxVgDzEGgKvSChxTlezI9HGve9I1zcXhtIMUBsp4CvBDpCqVSPGZdJ5AjUi/Kg+aYMpsSaLXGHxCxqecsUBpoTV5tgyeLyw38d588UnSt1RWy15lUHqSUVyTA2MeSH+b0iueixb46WettZL5FInObE2OuJu2kWvIJ2U05AWpX7uVDMNepoaQvqpyQ9lqOt1HCMVi879y00jh0gnycWx4V2I7WhFpkkcHhmHbFy+IeH7aML7A0ZhY50tJ2u/chOgN0qjrnp+eZzIrlcjQ69LY53AvMGJNwlLYHFgbKG8sdMwNXpUz82Z617tsB/co2ethqdkhbDUVniwAd0MCoDWgtvfjL/iccHT/3dVoo4z/M0Rsmpc6rsw5nU=
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook
      namespace: a2w-sre
