apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reminders-cron-secret
spec:
  encryptedData:
    secret: AgCgUSiVwkJ+JXxPSB4Mk68C9b8SaqrX4kR8AHoUYXWErOcy5VzF9fyBaB182V81x+uVr7h+0zZkJo+mGsAgA6ctm2rAVUa62iRXo5hzh2/NmvqaoQ9ieJ0zRkomfVEQC0yxVzuPtcdfmhUD/d7eZjMZeYK2OtPhtT5y9/TekMDqiGDkQT0gORERKcRdksLda9FRfNJh29xsWjxTcjCERMKjd1Mn1njV9wmQks2E/6Rou4rA7jwNu9W/9bJziBsh8hmY92A+3I/GzO5aaxV7i+otuRnh8MpEjXEp0Mjhu9KIKYwv2u1CJfGMkio0/SeCTwZrtocEDwcdCgPcm3idDIRoFDlejGQB8E4mfa8tXG6HOWLYJkBpye8YKL+Yuh2zwjy7q/jLFB4KQRCeNI7wvHGIac39jL5S/JnlPnu55RfVRxUsXbBp4VUViZQMIVZZfyiZHwbH49mLpVbJyZoCgpChkAmHquFDRBnMnd6PFyVq4toJ3nHbnGi3VkANhLclsPn9N6KWEC+bmqVrjuBGpUXxmqY2sueJdX0oPOgA0zKPKvTMZPxAM2dxoehadxvlc6IFxO68jylRjJGuo/64cY9gstRBvL2/3pbTRsV99g76PZh2Wg1rI4N8vdThG4z31R3Llm5laNwb5yT1+IEgFtZTVw0gtxe8QvZVVRJ/HcHPp7WGD0x2J50r0KN7/y6r9w5N4DosAKtFdxRfMqMChSjg3x39Vpg2LSKSGb507yJjidPcyA==
  template:
    metadata:
      name: reminders-cron-secret
    type: Opaque
