apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reminders-cron-secret
  namespace: argocd
spec:
  encryptedData:
    secret: AgCIZKAInJHEDS/bPXodqngj7Xqs5JCOnPpWDikTffdohus3shNeZnRjwgYAXwrtRynke5vCDQyLpnJ2MsqEkjD3mdElKIbIxn+Nt6EZarve9bn0MpfQmbNC1iS7MmjEzWkDjgCMwsuqRE8FnxGEkAF6LQ3FcdLwZkqelHL1OHNc+BgHh74Mrh2LDEnYWs42NKWidysV/KujnoEzFQTtV1GMgETGUafjYiXy7tYPXm06kATZipRlFPjJ8KeR525gZixWEXmwYAcpOGtd6YFBCy7eeb5NSxvwAHeGvdhah42FIWzLoiD1bJRGjmORGiHaZbsgOlamoHbDePES9kN3xCcGG+mq9Vvto3TIMmLG/mmxBHZAfTcclnv5ca2mrhSqHvt3yG1rLaX4zdgRIdUJNDBBp8/VnzLn0GXhXQEkrPpx4jK8VfVK8KWu53XYy8qxlwpbNhIU3URLdEdPPvDDouhWjMlZ1HxEAGkfS444sD6atPrptfBsY23sLJK7ZxDzMz2+70mU+kP6EPp7hGzjgfGq792WfZxrTM7hzxpTE3Q5U444hsOjSX6BKzfZmnmoPCk352WmRjDavPfcOihHZO9fg1IzGNyGuCPs4j9FPH0/wiLJ2ZVxJKAhVILzh6e95PWHx5RwNuX4GzAZ48jIQN/1CpepPccLXnCV1NIJFJSu454pGh7VB5WkUjGAI62h/6W5FWRLkhVOFZ+KQ9XOLTsgZoExAkg+zeBKsYRCRzphv0fC8w==
  template:
    metadata:
      creationTimestamp: null
      name: reminders-cron-secret
      namespace: argocd
    type: Opaque
