apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2w
  namespace: a2w
  labels:
    app: a2w
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2w
  template:
    metadata:
      labels:
        app: a2w
    spec:
      containers:
      - name: a2w
        image: registry.digitalocean.com/kubeden/a2w/landing:v3
        ports:
        - containerPort: 3000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: a2w-secrets
              key: openai-api-key
        - name: BEEHIIV_API_KEY
          valueFrom:
            secretKeyRef:
              name: a2w-secrets
              key: beehiiv-api-key
        - name: BEEHIIV_PUBLICATION_ID
          valueFrom:
            secretKeyRef:
              name: a2w-secrets
              key: beehiiv-publication-id
